name: Rust unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v4
    - run: make extract_test_data
    - run: |
        cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

    - name: upload codecov
      # You may pin to the exact commit or the version.
      # uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378
      uses: codecov/codecov-action@v4.5.0
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        # Repository upload token - get it from codecov.io. Required only for private repositories
        # token: # optional
        # Specify whether the Codecov output should be verbose
        verbose: true
        fail_ci_if_error: true
        file: ${{ steps.coverage.outputs.report }}
